site_name: FJCU CPC 訓練網

nav:
  - 首頁: index.md
  - 語法篇:
    - 基本介紹: syntax/intro.md
    - 基本資料型態: syntax/type.md
    - 輸入輸出: syntax/inputOutput.md
    - 運算子: syntax/operator.md
    - 條件判斷: syntax/condition.md
    - 迴圈: syntax/loop.md
    - 字串: syntax/string.md
    - 陣列: syntax/array.md
    - 函式與遞迴: syntax/functionAndRecursive.md
    - struct: syntax/struct.md
  - 雜項:
    - 複雜度: other/complexity.md
    - define: other/define.md
  - 資料結構:
    - STL: dataStructure/stl.md
    - 堆疊: dataStructure/stack.md
    - 隊列: dataStructure/queue.md
    - List: dataStructure/list.md
    - heap: dataStructure/heap.md
    - 二元平衡樹: dataStructure/bst.md
  - 基礎演算法:
    - 何謂演算法: algorithm/algorithm.md
    - 枚舉: algorithm/enumerate.md
    - 二分搜: algorithm/binarySearch.md
    - 分治: algorithm/divideAndConquer.md
    - 貪心: algorithm/greedy.md

python:
   version: 2 # for unicode
   setup_py_install: true

#the third-party extenison mdx_math.py comes with a setup.py script
# Thank you Dmitry Shachnev (https://github.com/mitya57/python-markdown-math) 
markdown_extensions: 
    - mdx_math:
        enable_dollar_delimiter: True #for use of inline $..$

# Required to load the MathJax javascript for the mdx_math.py
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']